OverloadingOperations.cs
De-Len/2_Semester-attestation pull request #3
Opened 2024-02-23 08:01 UTC by prince-de-len

2024-02-23 08:24 UTC, Hamjoshua commented
Тебе нужно:
Создать пользовательские классы Исключений и реализовать их
обработку.

Реализовать тестовое приложение «Матричный калькулятор» для
демонстрации работы созданного класса.

2024-02-23 08:24 UTC, Hamjoshua commented
Отправлено на переработку

2024-02-26 02:25 UTC, Hamjoshua commented on Program.cs
> +    static readonly Random random = new Random();
Поля\свойства либо с большой буквы, либо с маленькой. Тут надо random с большой буквы

2024-02-26 02:25 UTC, Hamjoshua commented on Program.cs
> +        for (var rowOfMatrix = 0; rowOfMatrix < Matrix.GetLength(0); ++rowOfMatrix)
здесь то же самое - _R_owOfMatrix

2024-02-26 02:44 UTC, Hamjoshua reviewed
Небольшие дефекты в наименовании и логики

2024-02-26 02:44 UTC, Hamjoshua commented on Program.cs
> +        int[,] result = new int[Rows, Columns];
result не слишком понятная переменная

2024-02-26 02:44 UTC, Hamjoshua commented on Program.cs
> +                if (matrix1.Value[IndexOfRow, IndexOfColumn] <= matrix2.Value[IndexOfRow, IndexOfColumn])
Если перегружается оператор <, то здесь ожидается <, а не <=.

2024-02-26 02:44 UTC, Hamjoshua commented on Program.cs
> +    public int GetLength { get; set; }
Get - слово, присущее для метода. Для поля нужно другое. Например Length
Также не вижу, чтобы данное поле что-то возвращало, геттер не прописан

2024-02-26 02:44 UTC, Hamjoshua commented on Program.cs
> +    public static int[,] ConvertMatrixToDouble(double[,] inputMatrix) // Приведение типов
Метод вроде должен возвращать матрицу с типом дабл, но при этом возвращает матрицу с типом инт

2024-02-26 02:44 UTC, Hamjoshua commented on Program.cs
> +class SquareMatrixDimensionsException : Exception
Вижу кастомную ошибку, хорошая работа

2024-02-26 02:44 UTC, Hamjoshua commented on Program.cs
> +        ExampleMatrix1.Clone();
В чем смысл этой строки? Значение просто возвращается и ни к какой переменной не стыкуется. Можно было бы ее запихать в вывод, но у тебя уже есть метод для вывода объекта PrintClone. Следовательно, лучше убрать эту строку

2024-02-26 07:49 UTC, prince-de-len commented on Program.cs
> +    public static int[,] ConvertMatrixToDouble(double[,] inputMatrix) // Приведение типов
Это же приведение типов? Насколько я понял, это изменение типа данных?

2024-02-26 14:06 UTC, Hamjoshua requested changes
Последний рывок и программа будет готова к мерджу на test

2024-02-26 14:06 UTC, Hamjoshua commented on Program.cs
> +        int LenthgtOfMatrix = matrix.GetLength(0);
*LengthOfMatrix

2024-02-26 14:06 UTC, Hamjoshua commented on Program.cs
> +        return subMatrix;
subMatrix с маленькой буквы

лучше сразу условиться - переменные с большой или маленькой? В соглашении написано, что PascalCase. Но половина интернета безбожно пишет с маленькой. Этих грешников можно простить, их большинство

Если решил следовать силам света, то следи, чтобы все переменные (кроме полей аргументов и приватных переменных, которые еще снабжаются "_") были с большой буквы

2024-02-26 14:06 UTC, Hamjoshua commented on Program.cs
> +    public static int[,] ConvertMatrixToDouble(double[,] inputMatrix) // Приведение типов
Рекомендую к прочтению эту статью

https://metanit.com/sharp/tutorial/3.37.php

2024-02-26 14:06 UTC, Hamjoshua commented on Program.cs
> +    public void PrintMatrix()
Я считаю все Print методы избыточными. Задача этого класса - давать результат, дискриминант, обратную матрицу и т.д. О выводе информации в читаемом варианте пусть заботится другой модуль

2024-02-26 14:06 UTC, Hamjoshua commented on Program.cs
> +            Console.WriteLine($"Ошибка: Вы ничего не ввели!");
А что, если пользователь в поле для ввода размера введет не пустую строку, а просто строку? Например "аоыафа". Пользователь будет удивлен, когда на "аоыафа" программа ему скажет, мол он ничего не ввел. Есть два стула - либо сделать общий вывод "Неправильный ввод!", либо же обработать каждую ошибку
В случае поступления пустой строки - вы ничего не ввели
В случае поступления букв и прочего, что не является цифрами - вы ввели не цифры

2024-02-26 14:06 UTC, Hamjoshua commented on Program.cs
> +            Console.WriteLine($"Ошибка: Вы ничего не ввели!");
К тому же, программа не останавливается и не пытается получать эти значения заново. Она просто продолжается, что может привести к ошибке кода. Лучше зациклить ввод значений, пока не пользователь не введет значение в правильном формате

2024-02-26 14:06 UTC, Hamjoshua commented on Program.cs
> +
Следи за тем, чтобы у тебя не было слишком много пустого пространства

Но и за тем, чтобы оно было: Между логическими блоками должен быть один Enter

2024-02-26 14:06 UTC, Hamjoshua commented on Program.cs
> +
Между функциями Enter нужен в любом случае. Как и между классами. Enter'ы внутри кода по твоему усмотрению, но советую членить логически связанные блоки Enter'ами

2024-02-26 14:06 UTC, Hamjoshua commented on Program.cs
> +    static readonly Random Random = new Random();
"При работе с полями static, являющимися private или internal, используйте префикс s_, а для статического потока используйте t_."

Здесь: s_camelCase

2024-02-26 14:06 UTC, Hamjoshua commented on Program.cs
> +    int[,] Matrix;
"При именовании private или internal полях и префиксе _их используйте верблюдьи регистры ("верблюдьи"). Используйте регистр верблюда при именовании локальных переменных, включая экземпляры типа делегата."

Приватные поля и свойства нужно правильно именовать - _camelCase

2024-02-26 14:06 UTC, Hamjoshua commented on Program.cs
> +        int LenghtOfMatrix = matrix.GetLength(0);
*LengthOfMatrix. Перепроверь правильное написание слов

2024-02-26 14:06 UTC, Hamjoshua commented on Program.cs
> +    public int[,] Value { get { return Matrix; } }
Value применимо, если в нем содержится одно значение. Если значений несколько, лучше назвать поле по-другому. Items, к примеру

2024-02-26 14:06 UTC, Hamjoshua commented on Program.cs
> +    //ПРОЧИЕ МЕТОДЫ
между "//" и комментарием должен быть пробел
"// хороший комментарий"

2024-02-26 14:06 UTC, Hamjoshua commented on Program.cs
> +class Program
Пока задачи небольшие, можно размещать в одном файле несколько объектов - исключения, классы, матричный калькулятор
Но задачи будут усложняться, классы раздуваться, строки доходить до 1000-ных значений. Это будет тяжко читать
На будущее - разделяй объекты на отдельные файлы. В одном пусть лежат все ошибки, в другом все возможные варианты матрицы, в третьем матричный калькулятор

2024-02-26 16:01 UTC, Hamjoshua requested changes

2024-02-26 16:01 UTC, Hamjoshua commented on Program.cs
> +            Console.WriteLine($"Ошибка: Вы ничего не ввели!");
Кстати, пользователь может ввести -1. Это тоже нужно обработать

2024-02-27 12:48 UTC, Hamjoshua requested changes
Требуются небольшие изменения

2024-02-27 12:48 UTC, Hamjoshua commented on Program.cs
> +    public int Length { get; set; }
Это поле не содержит никакой логики в геттере/сеттере, но при этом используется 4 раза. Что оно должно возвращать, если оно никак не задается?

2024-02-27 12:48 UTC, Hamjoshua commented on Program.cs
> +    public double Determinant { get; set; }
Поле было объявлено, но ни разу не использовалось

2024-02-27 12:48 UTC, Hamjoshua commented on Program.cs
> +        double Determinant = CalculateDeterminant(matrix);
у тебя CalculateDeterminant вызывается два раза. Это значит, что машина два раза пройдется по сложному алгоритму в случае ненулевого детерминанта

Здесь лучше заранее найти детерминант, использовать его в условии и работать с ним дальше

2024-02-27 12:48 UTC, Hamjoshua commented on Program.cs
> +                if (SizeOfMatrix1 != 0 &&  SizeOfMatrix2 != 0)
Число может быть отрицательным, и здесь лучше написать условие > 0

2024-02-27 12:48 UTC, Hamjoshua commented on Program.cs
> +                if (SizeOfMatrix1 != 0 &&  SizeOfMatrix2 != 0)
Также пользователю будет не совсем ясно, почему он ввел 0, а его начали снова просить ввести размеры матриц. Пользователя сначала нужно "отругать" за неправильное действие, а потом просить ввести размеры заново

сделай блок else, который будет подсказывать "Размер должен быть больше 0!"

2024-02-27 12:48 UTC, Hamjoshua commented on Program.cs
> +        int Rows1 = matrix1.Value.GetLength(0);
Не самое лучшее имя для переменной, что означает количество рядов. Потому что под Rows вполне воспринимается массив/список/коллекция из рядов матрицы. Лучше назвать RowCount, или RowLength. И так со всеми. 

Цифру в конце писать можно

2024-02-27 12:48 UTC, Hamjoshua commented on Program.cs
> +        int Rows1 = matrix1.Value.GetLength(0);
Поменяй везде, ибо Row/Column в данном контексте воспринимается как одномерный массив. У тебя же это имя переменной применятся в случаях, где участвуют индексы этих массивов. Повнимательнее

2024-02-28 13:50 UTC, Hamjoshua commented
Одобрено

2024-02-28 13:51 UTC, Hamjoshua approved these changes
Все четко

2024-02-28 13:55 UTC, merged